### ISSUE TITLE
Consistency with python.org styling

### ISSUE THREAD

**Issue by pradyunsg** [python/python-docs-theme#10]
Currently, the look of python.org is very different from that of docs.python.org. They should probably look more similar.

<img width="1680" alt="screen shot 2018-01-20 at 12 19 49 pm" src="https://user-images.githubusercontent.com/3275593/35180755-3c668424-fddc-11e7-9ba6-014787ed975e.png">
<img width="1680" alt="screen shot 2018-01-20 at 12 20 23 pm" src="https://user-images.githubusercontent.com/3275593/35180761-4c24d3f2-fddc-11e7-82b2-550779e84b87.png">

If nothing else, I feel at least the black top-bar for navigation with various python.org related sites should be brought over.

**Comment by Mariatta** [comment]
These are two different things and purpose.

Unifying the style will be huge effort I imagine, and needs to be coordinated with pythondotorg team 
https://github.com/python/pythondotorg

**Comment by Mariatta** [comment]
> I feel at least the black top-bar for navigation with various python.org related sites should be brought over.

-1 I'd prefer to keep docs.python.org simply about the docs of Python standard library

**Comment by Ivoz** [comment]
You could try an borrow some colours (although the yellow might be tricky use except, except on top of blue backgrounds), and some of the heading fonts, perhaps?

**Comment by pradyunsg** [comment]
> Unifying the style will be huge effort

Yep. Definitely. I just wanted to put this idea "out there" and see if there's any interest.

>> If nothing else, I feel at least the black top-bar for navigation with various python.org related sites should be brought over.
>
> -1 I'd prefer to keep docs.python.org simply about the docs of Python standard library

Just in case I wasn't clear, I'm suggesting of using the top-bar (the one with links to PyPI, Docs, Jobs and all) like Ubuntu does (see top of https://www.ubuntu.com, https://www.askubuntu.com and the likes). I felt that's sort of a nice middle ground here.

**Comment by JulienPalard** [comment]
@BrunoMaugery any advice on this?

**Comment by Mariatta** [comment]
> Just in case I wasn't clear, I'm suggesting of using the top-bar (the one with links to PyPI, Docs, Jobs and all) like Ubuntu does (see top of https://www.ubuntu.com, https://www.askubuntu.com and the likes). I felt that's sort of a nice middle ground here.

Thanks, it was clear to me the first time. I just think some of those links are just not relevant in docs.p.o, or for other projects adopting this styling.

I suggest keeping things as is for now.

**Comment by pradyunsg** [comment]
> I suggest keeping things as is for now.

Okay. =)

**Comment by pradyunsg** [comment]
I'll let this stay open for a while, just in case it might get some interest.

**Comment by pradyunsg** [comment]
Closing since there's clearly no interest.
