### ISSUE TITLE
Footer nav and copyright text not visible at low viewport widths in docs

### ISSUE THREAD

**Issue by ynaveenkmr** [python/python-docs-theme#100]
Hi team i founded on bug, Please check attached screenshot which I highlighted in it looks some text is missing it might be the alignment issue.
Alignment Issue in this page :- https://docs.python.org/3/tutorial/interpreter.html
<img width="50%" src="https://user-images.githubusercontent.com/17852890/206207715-90e6408f-d402-45e0-8a05-092e0c4eabf7.png">

Thanks & regards
Naveen
ynaveenkmr@gmail.com

**Comment by hugovk** [comment]
Please see PR https://github.com/python/python-docs-theme/pull/106 to only apply `margin-top: -2em` for desktop (1024+ pixels).
