### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by hugovk** [python/python-docs-theme#109]
The last release was https://github.com/python/python-docs-theme/releases/tag/2022.1 in January 2022.

There's been a few bug fixes merged since then:

* https://github.com/python/python-docs-theme/compare/2022.1...main

Notably:

* https://github.com/python/python-docs-theme/pull/104
* https://github.com/python/python-docs-theme/pull/96
* https://github.com/python/python-docs-theme/pull/106
* https://github.com/python/python-docs-theme/pull/108

My main motivation for a release is the dark theme: https://github.com/python/python-docs-theme/pull/44

I think it's ready for merge and release, but if we want to be safe, I suggest we make one release with the bugfixes, followed by another with the dark theme. That gives us the option to easily rollback in case there are any big issues.

cc @JulienPalard and @Mariatta :)

**Comment by JulienPalard** [comment]
Working on it!

**Comment by JulienPalard** [comment]
@hugovk done.

**Comment by hugovk** [comment]
I restarted https://github.com/python/cpython/actions/runs/4403319435 and it passed now.

Thank you!
