### ISSUE TITLE
Is suffixing version in the dev tree with `dev` usefull to someone? 

### ISSUE THREAD

**Issue by JulienPalard** [python/python-docs-theme#111]
The current `CONTRIBUTING.rst` tells to bump to a dev version after releasing:

```
- bump version (YYYY.MM.dev) in setup.py and python_docs_theme/theme.conf
- Commit this last bump.
- push and push the tag (``git push && git push --tags``)
```

Is it really usefull? I don't contribute a lot to this repo and I don't feel it's usefull for me, but if it's usefull for you please tell.

@willingc I don't remember why it's here, `git log` tells it's me but I think I copy-pasted this sequence of tasks from way before me, mabe you gave it to me and you now better?

**Comment by Mariatta** [comment]
The `.dev` is to show that this version has been merged to main but not yet published to PyPI.
Before publishing to PyPI we remove the `.dev`.
I think the `.dev` is just for (perhaps uncommon) situation in case there are people installing the package from source, and found bugs, and want to file bugs against it, we can find out exactly which version they're using.

**Comment by Mariatta** [comment]
If we always release after merging then perhaps the dev won't be needed.

**Comment by JulienPalard** [comment]
> Before publishing to PyPI we remove the .dev.

As stated in contributing, it's added after pushing to PyPI.

I'm proposing to remove this step from the `CONTRIBUTING.rst` file for now.

**Comment by pradyunsg** [comment]
> As stated in contributing, it's added after pushing to PyPI.

Yes, and it's removed prior to publishing to it as well ("bump version (YYYY.MM) in pyproject.toml"). It still serves the purpose that @Mariatta describes in her comment.
