### ISSUE TITLE
Dark theme: "Hide Search Matches" shown on mobile

### ISSUE THREAD

**Issue by hugovk** [python/python-docs-theme#117]
1. Using the new dark theme (#44) in mobile layout: https://docs.python.org/dev/
2. Search for something (e.g. "turtle")

<img width="612" alt="image" src="https://user-images.githubusercontent.com/1324225/226134240-49818027-6071-44e4-b392-102237337e81.png">

3. Click a result

<img width="612" alt="image" src="https://user-images.githubusercontent.com/1324225/226134261-274152a7-0b52-427e-8ee4-672b5445c955.png">

Actual result: "Hide Search Matches" is shown subscript to the right of the search box

<img width="612" alt="image" src="https://user-images.githubusercontent.com/1324225/226134268-92ad51ec-8728-4fa5-9299-dfb9a92a6dc0.png">

Expected result: It's either shown more neatly, or, like desktop view, isn't shown at all:

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1324225/226134330-11fb5888-3bd9-4a46-b2bd-e5924ce73636.png">

cc @septatrix

**Comment by septatrix** [comment]
Okay I found the culprit/fix to restore the previous behaviour (not shown at all). Do we want that or would it actually be desirable to show it?

**Comment by septatrix** [comment]
Given that it is only ever added to either the mobile UI or the desktop UI I feel like it is probably less confusing to suppress it again, aye?

**Comment by rik** [comment]
Besides the UI glitch, I was actually glad to discover this "bug" as I'm not fond of matches being highlighted.

I wish it was available on the wide screen UI too.

**Comment by hugovk** [comment]
> I wish it was available on the wide screen UI too.

You can press <kbd>esc</kbd> to remove the highlights.

---

> Given that it is only ever added to either the mobile UI or the desktop UI I feel like it is probably less confusing to suppress it again, aye?

Yeah, no strong opinion from me, if in doubt let's go for the previous behaviour. Thank you!

**Comment by hugovk** [comment]
@septatrix Would you be able to restore the previous behaviour? For me, this is the only one of the reported issues I'd like fixed before deploying this more widely. And I've heard lots of good feedback about the dark theme!

**Comment by septatrix** [comment]
> @septatrix Would you be able to restore the previous behaviour? For me, this is the only one of the reported issues I'd like fixed before deploying this more widely. And I've heard lots of good feedback about the dark theme!

Done, please see if #124 is fine
