### ISSUE TITLE
Color change

### ISSUE THREAD

**Issue by JulienPalard** [python/python-docs-theme#125]
I don't know if it's intentional, but for me color changed since the lasts commits, see https://docs.python.org/3.12/tutorial/introduction.html#first-steps-towards-programming for example vs 3.11:

![Screenshot 2023-04-13 at 16-11-37 3  An Informal Introduction to Python](https://user-images.githubusercontent.com/239510/231786079-97ed999f-5e63-4fb4-82c5-50ac0a9d4904.png)

![Screenshot 2023-04-13 at 16-11-44 3  An Informal Introduction to Python](https://user-images.githubusercontent.com/239510/231786072-0be7a1af-3873-4ecc-be50-dec0a1c36ac2.png)

**Comment by hugovk** [comment]
As it happens, @lolbat said last week he found the green background hard to read if you're at all red/green colourblind:

https://mastodon.social/@lolzac@home.social/110147582722352531

He suggested a blue-grey something like the top one here:

![image](https://user-images.githubusercontent.com/1324225/231798659-093e0117-d9ec-43c9-ab0c-10ca686fa072.png)

**Comment by rajneesh-18** [comment]
How to contribute in this repo ?

**Comment by hugovk** [comment]
The change was intentional, let's close this.
