### ISSUE TITLE
Make theme safe for parallel reading?

### ISSUE THREAD

**Issue by pitrou** [python/python-docs-theme#13]
When trying to run sphinx-build with `-j16`, I get the following warning:
```
WARNING: the python_docs_theme extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read
```

**Comment by jonparrott** [comment]
If you want to test it out and see if it's fine with parallel read, I'm happy to merge a PR to add this.

**Comment by pitrou** [comment]
What is required to declare it safe? Not a Sphinx theme expert :-)

**Comment by jonparrott** [comment]
Seems to be covered here http://www.sphinx-doc.org/en/stable/extdev/#extension-metadata

**Comment by pitrou** [comment]
Ok, I tested it on the CPython docs and it worked fine.

**Comment by jonparrott** [comment]
Cool, want to send a PR?

**Comment by pitrou** [comment]
Hmm, I've just deleted my `python-docs-theme` clone... AFAIR it's just a remember of returning the required dict from `setup()` in `__init__.py`.

**Comment by jonparrott** [comment]
No worries, I'll make it happen.
