### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by hugovk** [python/python-docs-theme#143]
Please could we have a new release?

Release instructions are at https://github.com/python/python-docs-theme/blob/main/CONTRIBUTING.rst, the first two steps have been done in https://github.com/python/python-docs-theme/pull/142 calling it 2023.7. We could call it 2023.8 instead, but I don't mind.

**Comment by Mariatta** [comment]
v 2023.7 released. https://pypi.org/project/python-docs-theme/2023.7/

**Comment by hugovk** [comment]
Thank you!

PR to upgrade: https://github.com/python/cpython/pull/107617
