### ISSUE TITLE
Incorrectly highlighted paragraph in dark theme

### ISSUE THREAD

**Issue by Eclips4** [python/python-docs-theme#149]
Using dark theme [this paragraph](https://docs.python.org/3.13/howto/isolating-extensions.html) looks unreadable:

![image](https://github.com/python/cpython/assets/80244920/33632b79-250a-4879-ba78-71d429617654)

**Comment by AA-Turner** [comment]
We exclude 2023.7 (https://github.com/python/cpython/pull/107666) due to https://github.com/python/python-docs-theme/issues/144. #146 was merged to revert, but there hasn't been a new release yet (#148).

A

**Comment by hugovk** [comment]
Looks this is a fresh bug not covered by https://github.com/python/python-docs-theme/pull/138, I'll make a PR and then let's do a release.

**Comment by hugovk** [comment]
Please see PR https://github.com/python/python-docs-theme/pull/150.
