### ISSUE TITLE
Dark mode: highlighted footnote unreadable

### ISSUE THREAD

**Issue by hugovk** [python/python-docs-theme#161]
1. Go to https://docs.python.org/3.13/library/gettext.html (uses Sphinx 6.2.1)
2. Switch to dark mode if in light
3. Click the "[1]" or "[2]" link to jump to the footnote

Expected result: Text is readable

Actual result: Uses a yellow background suitable for light mode, not dark, making text unreadable:

<img width="834" alt="image" src="https://github.com/python/python-docs-theme/assets/1324225/7b62c0f4-250e-4e38-b895-be9c137efb8b">

This is because of this CSS in https://docs.python.org/3.13/_static/basic.css:

```css
.footnote:target {
    background-color: #ffa;
}
```

This CSS comes from Sphinx:

https://github.com/sphinx-doc/sphinx/blob/35965903177c6ed9a6afb62ccd33243a746a3fc0/sphinx/themes/basic/static/basic.css_t#L715-L717

But I guess we should fix it in this theme?

Note: Cannot reproduce with https://docs.python.org/3.12/library/gettext.html because it uses Sphinx 4.5.0, and the CSS only applies to the structure in 5+.

**Comment by ferdnyc** [comment]
> Note: Cannot reproduce with https://docs.python.org/3.12/library/gettext.html because it uses Sphinx 4.5.0, and the CSS only applies to the structure in 5+.

Bummer: Now it *can* be reproduced there. I guess the site pulled in Sphinx updates, but not updates to the theme!

**Comment by hugovk** [comment]
It's not releases yet :) https://github.com/python/python-docs-theme/pull/162#issuecomment-1911546345

But thanks for the ping!
