### ISSUE TITLE
Dark theme: "class" is unreadable

### ISSUE THREAD

**Issue by jrial** [python/python-docs-theme#199]
# Documentation

The word "class" before class names in the documentation is unreadable when browsing with the dark theme.

Example from the [set/frozenset docs](https://docs.python.org/3/library/stdtypes.html#set-types-set-frozenset):

![image](https://github.com/user-attachments/assets/34f42073-a7aa-446a-ad19-17cc19d79a61)

**Comment by Wulian233** [comment]
The document has a dark and light theme mode, did you use the site's dark mode or did some browser plugin enforce the dark mode? This kind of coercion can have some problems, and the built-in dark mode works fine


![IMG_20241002_221739.jpg](https://
github.com/user-attachments/assets/afb6e2e1-412e-4836-87fd-efca3b0da0ce)

![IMG_20241002_221747.jpg](https://github.com/user-attachments/assets/1a162957-f8f4-42c8-b0fe-88d348331729)

**Comment by jrial** [comment]
You're correct. Turns out it was a browser extension. Sorry for the noise. Closing.
