### ISSUE TITLE
Add `python-docs-theme` to `python` PyPI organisation

### ISSUE THREAD

**Issue by hugovk** [python/python-docs-theme#205]
Following https://discuss.python.org/t/request-python-organisation-on-pypi/26545, let's add this package into the either then https://pypi.org/org/cpython/ or https://pypi.org/org/python/ organisations.

The main benefits are:

* Visibility: we'll be able to see our packages under a PyPI org page

* Maintainability: we can share granular PyPI access to improve the bus factor

We should decide which org to move this package.

**Comment by hugovk** [comment]
@encukou [said](https://discuss.python.org/t/request-python-organisation-on-pypi/26545/10):

> My thinking is that `blurb` & `cherry-picker` are `cpython`-specific, but `python-docs-theme`, used by [PyPA](https://www.pypa.io) or [typing](https://typing.readthedocs.io), might be better in `python`.

I [said](https://discuss.python.org/t/request-python-organisation-on-pypi/26545/12) I don't mind too much either way, but the [`python-docs-theme` README](https://github.com/python/python-docs-theme) does point out:

> Note that when adopting this theme, you're also borrowing an element of the trust and credibility established by the CPython core developers over the years. That's fine, and you're welcome to do so for other Python community projects if you so choose, but please keep in mind that in doing so you're also choosing to accept some of the responsibility for maintaining that collective trust.

I think that tips it more towards the `cpython` side in the [SC categorisation](https://discuss.python.org/t/request-python-organisation-on-pypi/26545/5)?

> * `cpython`: for development tools that are tied fairly closely to CPython development. This could for example include blurb and cherry-picker. Users generally shouldn’t have to care except for developing CPython itself (although that doesn’t mean the tools necessarily have to be unusable for anyone else).
> * `python`: for general-audience projects that are maintained the Python Core Devs. An example for this category would be tzdata.

**Comment by Mariatta** [comment]
I actually think this theme would fit better under the `python` org instead of the `cpython` org. But I also wouldn't mind to put it under `cpython`. In the end, it would be easy enough to transfer out to the other org.

**Comment by hugovk** [comment]
Thanks for the feedback, let's go ahead with `python`.

@Mariatta Please could you add `python-docs-theme` to the `python` org?

https://pypi.org/manage/organization/python/projects/

Here are the current listed maintainers, in case we need to re-add them:

<img width="202" alt="image" src="https://github.com/user-attachments/assets/6467928e-4236-421c-b475-c1e7acde3845">

**Comment by hugovk** [comment]
@Mariatta Please could you add this project to the `python` org, or add me as an "owner"? Thank you!

**Comment by Mariatta** [comment]
Sorry I missed the message earlier. I have just moved the project, however it seems that my access to the project was removed after the transfer, eg it removed me from the maintainers list for python-docs-theme on PyPI.

https://pypi.org/project/python-docs-theme/

Can you please add me back to the project as a maintainer?

I described the bug in https://github.com/pypi/warehouse/issues/17311

**Comment by hugovk** [comment]
Thank you! It was originally just before PyLadiesCon so I imagine you were rather busy at the time :)

I see Mike added you back in https://github.com/pypi/warehouse/issues/17311#issuecomment-2557877454 👍
