### ISSUE TITLE
Preview of Docs is broken

### ISSUE THREAD

**Issue by StanFromIreland** [python/python-docs-theme#208]
Firefox on Windows 11

https://python-docs-theme-previews.readthedocs.io/

The Preview mentioned in the README never loads. 

Errors:
```
Cookie “_cfuvid” has been rejected for invalid domain. 
Error registering page view
```

**Comment by hugovk** [comment]
It's working for me in Chrome on macOS and Android. Could you clear your cache and try again?

**Comment by StanFromIreland** [comment]
Weird, seems to work now. I had cleared it before (CTRL+SHIFT+R) but there was no change.
