### ISSUE TITLE
Where to report bugs?

### ISSUE THREAD

**Issue by v-python** [python/python-docs-theme#21]
https://docs.python.org/3/bugs.html tells me to go to bugs.python.org.
But when I did, I was told to come here.
This wastes users time, not knowing where to go.

**Comment by pfmoore** [comment]
There's a difference between reporting bugs in the *content* of the documentation (for which bugs.python.org is correct) and reporting bugs in the *presentation* of that content (which is here).

Agreed the docs should make that distinction.

**Comment by JulienPalard** [comment]
What about the paragraph

```
If you find a bug in the theme (HTML / CSS / JavaScript) of the
documentation, please submit a bug report on the `python-doc-theme bug
tracker <https://github.com/python/python-docs-theme>`_.
```

being added in bugs.html?

**Comment by encukou** [comment]
Added in https://github.com/python/cpython/pull/117989
