### ISSUE TITLE
Make the python documentation responsive for smaller viewports

### ISSUE THREAD

**Issue by karlcow** [python/python-docs-theme#30]
Currently the theme is desktop only which makes the python documentation not very readable/accessible on mobile. 

There was an issue on the python project created 4 years ago to address this problem.
https://bugs.python.org/issue23312

Since then the documentation theme has been separated in a different package.

**Comment by epicfaace** [comment]
Can we close this issue now? @JulienPalard

**Comment by karlcow** [comment]
agreed.
