### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by zware** [python/python-docs-theme#37]
Hi, can we get a release of this with the latest fixes?  In particular, we're getting reports about the broken Sphinx link in the footer.

If there's anything I can do to help it along, please let me know.

**Comment by JulienPalard** [comment]
I think I don't have the rights on pypi.org/p/python-docs-theme, cc @Mariatta @theacodes @ncoghlan?

Also @ewdurbin could we please have a "pre-prod" server for docs.python.org to test this (and to test docsbuild-scripts, new languages, ...) before pushing it to production?

**Comment by Mariatta** [comment]
I have admin right. Let me know what I should be doing there...

**Comment by Mariatta** [comment]
just publish this to pypi?

**Comment by JulienPalard** [comment]
@Mariatta no no no! Publish this to pypi WHILE crossing fingers it won't break docs.python.org. I'll do too.

I'm really *not* a CSS guy, but I've read the 3 commits and it looks OK.

**Comment by zware** [comment]
We'll need a version bump and tag before publishing; I can see to that if you want.

**Comment by Mariatta** [comment]
😰been awhile since I have to publish to pypi manually using setuptools....

going through this checklist, and let me know if there are additional steps that I might miss
- [ ] bump version number?
- [ ] changelog?
- [ ] publish to test pypi?
- [ ] publish to real pypi?
- [ ] add .post1 to codebase?

**Comment by Mariatta** [comment]
Here it is: https://pypi.org/project/python-docs-theme/2020.1/ 🤞

**Comment by zware** [comment]
Thank you, @Mariatta!
