### ISSUE TITLE
Avoid italics and use monospace for function prototypes

### ISSUE THREAD

**Issue by JulienPalard** [python/python-docs-theme#42]
See https://bugs.python.org/issue38495

**Comment by Shivank98** [comment]
This issue seems to be with docs of python3.7 only. can I take this issue to solve?

**Comment by JulienPalard** [comment]
The fact that it only affects 3.7 made me search why. Looks like it has been done in 10be089395a0cb79aa50b41fddb62745476b1584, so now we "just" need to understand why it's not applied in 3.7.

Feel free to take a look at it, but maybe as the python-docs-theme is not pinned in docsbuild scripts nor in cpython, it just never updated, I'll probably have to check it myself on the server, hope I'll have time soon.

**Comment by pradyunsg** [comment]
Uhhhhh. I'm not a _huge_ fan of the patch from #25 -- the specific styling for this element comes from the pygments theme, which means that the fix is a bit of a bodge.

That said, I don't see the issue in 3.7's docs anymore and this can be closed IMO.

**Comment by JulienPalard** [comment]
I still see it in 3.7 where it looks like an empty string:

![Screenshot_2020-11-15 Built-in Functions — Python 3 7 9 documentation](https://user-images.githubusercontent.com/239510/99183214-72a5ff80-273a-11eb-9c79-05eb52de2328.png)

vs 3.8 were I clearly see it's a space:
![Screenshot_2020-11-15 Built-in Functions — Python 3 8 6 documentation](https://user-images.githubusercontent.com/239510/99183213-720d6900-273a-11eb-9322-3e7aaab108d5.png)

**Comment by JulienPalard** [comment]
python-docs-theme is not pinned, so the venv on the build server is probably just old, I'll check this.

**Comment by JulienPalard** [comment]
Oh, answer is simple, python-docs-theme was not separated in 3.7. And 3.7 is in security only, better keep things untouched. Bug is fixed for >=3.8, which is good enough.

**Comment by pradyunsg** [comment]
Awesome! Thanks for looking @JulienPalard! ^.^
