### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by vitaly-zdanevich** [python/python-docs-theme#43]
Please save our eyes. And batteries. Do not ignore this property of useragent https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

Cross-defect with https://bugs.python.org/issue39518

**Comment by opensource-assist** [comment]
@vitaly-zdanevich
How about <a href="https://chrome.google.com/webstore/detail/dark-theme-for-chrome/geooakdjiamlhpechokegobmhdmlgidk?h1=en">this</a>?

**Comment by vitaly-zdanevich** [comment]
I know about such extensions, but this is only for desktop browser. Youtube has dark theme, Google Calendar has dark theme on mobile - this is basic feature, dark theme is not for beauty - dark theme is against pain in eyes.

You need to add maybe 10 lines of CSS. I can do it if you approve me.

**Comment by opensource-assist** [comment]
@vitaly-zdanevich Why don't you do the PR on CPython's repo? The docs are served in there.

**Comment by vitaly-zdanevich** [comment]
But theme is in this repository.

**Comment by septatrix** [comment]
If you don't mind I'd like to work on this issue and make a pull request with some design drafts...

**Comment by vitaly-zdanevich** [comment]
Ok.

**Comment by septatrix** [comment]
Just pushed a first draft if you want to take a look (#44)...

**Comment by flying-sheep** [comment]
What’s missing before #44 will be merged?

**Comment by hugovk** [comment]
We're currently blocked due to lack of clarity whether we can use Sphinx 3 or need to keep support for 1.8:

https://github.com/python/python-docs-theme/pull/44#issuecomment-1116173455

**Comment by AA-Turner** [comment]
It was resolved to 3.2 (https://github.com/python/cpython/pull/93337), though the pin to `python-docs-theme==2022.1` should probably be introduced and backported to all non EOL versions, which are currently all unpinned (https://github.com/python/cpython/blob/3.7/Doc/requirements.txt#L18)

A
