### ISSUE TITLE
Make this available in PyPI?

### ISSUE THREAD

**Issue by Mariatta** [python/python-docs-theme#5]

**Comment by jonparrott** [comment]
I suggested this for both this repo and its downstream pypa-docs-theme, but @ncoghlan raised some concerns.

**Comment by JulienPalard** [comment]
There's https://pypi.python.org/pypi/python-docs-theme/ but with no files, do you remember the conerns?

**Comment by ncoghlan** [comment]
IIRC, my main question was just asking what we'd gain from the extra update publication overhead relative to having users install from the git repo.

I'm OK with "We want to set a good example" as an answer to that question, though :)

**Comment by ned-deily** [comment]
There is another (IMHO blocking) reason to make this available on PyPI: as it stands, if the changes associated with bpo-30607 / cPython PR 2017 were merged, this would introduce a new dependency on Git in the cPython Docs build.  Currently, there is no such dependency and, in fact, I know of at least one build process that depends on there being no dependency on Git.  This would also affect any builders from cPython source tarballs, unless the release process were changed to bundle the docs theme into the source tarball.  I would much prefer to see this as a PyPI download like the reset of the Docs build toolchain (e.g. Sphinx and friends).

**Comment by jonparrott** [comment]
Great point, Ned. Since I own the PyPI record already, it's trivial to get this published.

@ncoghlan @Mariatta would you like to also be added as package owners in case I disappear / go rogue ?

**Comment by Mariatta** [comment]
Thanks for asking :) Sure, feel free to add me.

**Comment by ncoghlan** [comment]
Aye, happy to be a backup publisher :)

**Comment by jonparrott** [comment]
Great. It occurs to me that we need to think of a versioning strategy. Should we just match Python major.minor?

**Comment by ncoghlan** [comment]
I'd suggest a date based version - that way if we decide to update the look & feel, we can make the decision on whether or not to update old maintenance branches at the same time.

**Comment by jonparrott** [comment]
SGTM. Created #11 and closing this as we've published. :)
