### ISSUE TITLE
Indicate that this project is being published to PyPI

### ISSUE THREAD

**Issue by webknjaz** [python/python-docs-theme#50]
Currently, it's totally unobvious just by looking at the repo that it's installable from PyPI. I'd be great to add a link in the URL field of this repo and maybe also add it (or a badge) to the README...

**Comment by Mariatta** [comment]
I think it's already addressed in https://github.com/python/python-docs-theme/pull/49

Additionally, the readme does say that you can `pip install python-docs-theme`

**Comment by webknjaz** [comment]
> I think it's already addressed in #49

I'm talking about the opposite: there's zero links to PyPI from this repo.

> Additionally, the readme does say that you can `pip install python-docs-theme`

Not anymore. https://github.com/python/python-docs-theme/pull/32 removed `pip install` from the README.
