### ISSUE TITLE
Untagged versions on PyPI

### ISSUE THREAD

**Issue by webknjaz** [python/python-docs-theme#51]
I've noticed that there's 4 releases on PyPI (2020.1, 2018.7, ￼2018.2, 0.0.1): https://pypi.org/project/python-docs-theme/2020.1/#history.

But in this repo there's only one tag for 2018.2 and that's it.

It's not clear what revisions were published to PyPI. It seems like this has been done using manual uploads and so I'd suggest to:
1) Find out the PyPI version to Git commit sha mappings and retrospectively tag them
2) Automate the publishing via GHA or literally anything else in order for the releases to be trackable with the logs publically available

**Comment by Mariatta** [comment]
Yes, publishing to PyPI has been manual work.
I'm all for automating it through GitHub Actions or any other means.
