### ISSUE TITLE
Switch to a system font stack?

### ISSUE THREAD

**Issue by pradyunsg** [python/python-docs-theme#55]
xref: https://github.com/pandas-dev/pydata-sphinx-theme/issues/247

Would a PR switching this theme to system fonts as per https://systemfontstack.com, be acceptable?

**Comment by Mariatta** [comment]
Is this the same issue as #54 ?

**Comment by pradyunsg** [comment]
No. That PR changes this theme to use `font-family: Arial, sans-serif`.

This one is suggesting we change to something like: `font-family: -apple-system, BlinkMacSystemFont, avenir next, avenir, helvetica neue, helvetica, Ubuntu, roboto, noto, segoe ui, arial, sans-serif;` instead, which is a strict superset.

The reasoning *why* we might want to use such a set of fonts, is presented pretty well on the aforementioned https://systemfontstack.com website. :)

**Comment by hugovk** [comment]
Might this also fix https://github.com/python/devguide/issues/581?

**Comment by pradyunsg** [comment]
That's because the font-stack is monospace, sans-serif and should instead be `monospace, monospace` because of a Chrome bug. 🤷🏽 

If a PR is welcome, we should probably change the monospace font stack too (there's an example in the link provided, so... that should fix it).

**Comment by hugovk** [comment]
> That's because the font-stack is monospace, sans-serif and should instead be `monospace, monospace` because of a Chrome bug. 🤷🏽

Oh! Here's more info on it: https://stackoverflow.com/a/36540436/724176

> That's right: _two_ `monospace` keywords at the end of the font stack. Nobody knows why this works; it just does.

It also links to a 2010 blogpost about it, and it's not going away anytime soon!

**Comment by pradyunsg** [comment]
Y'all can do this if you want, but I'm gonna close this so that it doesn't show up in my personal "Issues" list from the top-bar on GitHub when logged-in. :)
