### ISSUE TITLE
Python escape codes (\n, \t etc.) are missing the '\' for 3.8 and 3.9 docs

### ISSUE THREAD

**Issue by TizzySaurus** [python/python-docs-theme#63]
I believe [this commit](https://github.com/python/cpython/commit/dcc997cd28ab33ebac44182ee55533c1b37689f7) (as part of https://github.com/python/cpython/pull/23658) was intended to fix issues with the new way in which sphinx handles backslashes in the Python 3.10 documentation.

The issue is that this commit also applied to the 3.8 and 3.9 documentations, which doesn't have this new handling, and so results in escape codes (`\n`, `\t`, etc.) being escaped to just `n`, `t`, etc.
E.g. the [print documentation](https://docs.python.org/3.8/library/functions.html#print) has `end='n'` instead of `end='\n'`.

I'm guessing the files for the 3.8 and 3.9 docs just need to be reverted back to the files from before this commit.

NB: I'm not sure how the source links to different Python version's docs but the issue only applies to 3.8 and 3.9, not for the docs of Python <3.8 or >3.9.

P.S I've not used GitHub much and this is my first time delving into the python docs source so apologies if I've stated/linked anything incorrectly.

**Comment by JulienPalard** [comment]
Looks like https://github.com/python/cpython/pull/23658 should have not been backported, thanks for reporting.

I commented on https://github.com/python/cpython/pull/23827 and https://github.com/python/cpython/pull/23828 proposing a revert.

**Comment by JulienPalard** [comment]
@TizzySaurus This is in the right way to being fixed, the revert has been done, still have to proofread and merge, then the docsbuild-script will have to build the doc in production for it to update on docs.python.org, it should not take long.

As it's not a theme issue, I'll close this issue, you can keep track of it here now: https://bugs.python.org/issue42822

Again, thanks for reporting, and happy new year!
