### ISSUE TITLE
The 3.10 documentation has a horizontal scroll bar on mobile

### ISSUE THREAD

**Issue by verhovsky** [python/python-docs-theme#65]
Compare 3.9 vs 3.10:

![Screenshot 2021-01-15 at 12 10 53](https://user-images.githubusercontent.com/5687998/104757272-d9d83400-572a-11eb-97b7-5c0b9b0e9e91.png) ![Screenshot 2021-01-15 at 12 10 36](https://user-images.githubusercontent.com/5687998/104757273-da70ca80-572a-11eb-84a7-f8a24731cf1a.png) 

See https://github.com/python/cpython/pull/21376#issuecomment-761065453 though that change isn't what actually causes this, it seems to be the case on all documentation pages that I checked.

**Comment by verhovsky** [comment]
If you close the sidebar, you can't scroll all the way to the right

![Screenshot_20210123-054822](https://user-images.githubusercontent.com/5687998/105576137-c63a5800-5d3e-11eb-931c-455d8a6afd06.png)

**Comment by hugovk** [comment]
Links for reference:

* https://docs.python.org/3.9/library/functions.html
* https://docs.python.org/3.10/library/functions.html
