### ISSUE TITLE
Spaces in inline code are not monospace

### ISSUE THREAD

**Issue by verhovsky** [python/python-docs-theme#66]
because the CSS has `text-align: justify;` on the text, and inline code is a `<code>` tag with a bunch of `<pre>` tags, 

```html
<code class="docutils literal notranslate"><span class="pre">set('abc')</span> <span class="pre">==</span> <span class="pre">frozenset('abc')</span></code>
```

the spaces between the `<pre>` tags get expanded:

![Screenshot from 2021-01-21 23-43-46](https://user-images.githubusercontent.com/5687998/105447709-b9383e80-5c42-11eb-9790-eb9b86077f79.png)

https://docs.python.org/3/library/stdtypes.html#frozenset.copy

**Comment by philg314** [comment]
This has been fixed in https://github.com/python/python-docs-theme/pull/79 so this issue can be closed.
