### ISSUE TITLE
Language switcher disappears below 1024px

### ISSUE THREAD

**Issue by willingc** [python/python-docs-theme#73]
Thanks to @JulienPalard for deploying the new theme release: https://docs.python.org/3.11/

Below 1024px, the language switcher/selector disappears.

cc/ @obulat Thought you would enjoy seeing the theme deployed. It's a great improvement.

**Comment by obulat** [comment]
Thank you for deploying the theme on 3.11! I am really happy to see it 🎉 

The language switcher on mobile screen is inside the menu:

<img width="414" alt="Screen Shot 2021-05-09 at 8 32 21 AM" src="https://user-images.githubusercontent.com/15233243/117561632-185e7980-b0a1-11eb-95b6-4332f7d62e3d.png">

This way, the top bar is not too crowded, and users have enough space to use the search bar. 

We could also put the language switcher to the bottom, but some pages are quite long, and it would be difficult to get to.

I've also created a PR with some fixes: #74

**Comment by hugovk** [comment]
This is fixed now, thanks!
