### ISSUE TITLE
Theme: text justification looks bad (in narrow columns)

### ISSUE THREAD

**Issue by justvanrossum** [python/python-docs-theme#77]
I'm stoked to see the huge improvements of the docs on mobile. This is really fantastic.

One thing I noticed, though, is that there are often huge gaps between words. For example (on Android):
![image](https://user-images.githubusercontent.com/4246121/117572927-7f962100-b0d5-11eb-8652-2b0992392108.png)
Using "text-align: left" would make this look a lot better.

I would go further, and recommend to never ever use "justify" at all: it generally reduces readability and often simply looks bad. Even with wider columns it often becomes a typographic disaster (Safari, desktop):
![image](https://user-images.githubusercontent.com/4246121/117573235-0992b980-b0d7-11eb-824c-45e1aaff4de4.png)

**Comment by JulienPalard** [comment]
I don't know about the best practices about this. While I can understand the use of justify on multi-column displays (like printed newspapers) I don't feel it add any benefit on a single column of text, I'll be ok for this to be removed, but I bet many will complain too?

**Comment by hugovk** [comment]
Similarly justified text is bad for accessibility:

* https://www.w3.org/TR/WCAG20-TECHS/G169.html
* https://webaim.org/techniques/textlayout/

**Comment by JulienPalard** [comment]
@obulat PR fixing this can be tested at https://docs.python.org/3.10
