### ISSUE TITLE
Should the menu be pinned like it was in 2.7?

### ISSUE THREAD

**Issue by JulienPalard** [python/python-docs-theme#8]
While working on the doc with @FGuillet and @BrunoMaugery we spotted some javascript updating the position of the menu, like to "pin" it on the screen while scrolling, like 2.7 is still doing. We though it was just broken, but do we want to keep this feature? It looks like it causes jiterring problems in 2.7 https://bugs.python.org/issue32393.

**Comment by jonparrott** [comment]
i'm not a huge fan of pinning personally.

**Comment by septatrix** [comment]
I personally like the pinning as it gives me the possibility to jump to another section even when im halfway through the page.
Following a few redirects in the bug report you linked I was able to find this commit https://github.com/python/cpython/commit/8ab24b2ebcf99f703f00297cb3a0c3ff857eecf8. Apparently this fixes the issue. However this is not yet implemented in this theme but we probably could simply apply this patch here.
Does anyone know why there are apparently two different locations where this theme is maintained anyway?

**Comment by philg314** [comment]
This has been implemented in https://github.com/python/python-docs-theme/pull/91 so this issue can be closed.
