### ISSUE TITLE
py.svg not found on search result page

### ISSUE THREAD

**Issue by jugmac00** [python/python-docs-theme#80]
repro: 
- go to docs (Python 3.11)
- open dev console in browser
- search for e.g ."xml rpc"
-> 404 py.svg not found

or open dev console and got to this URL directly:
https://docs.python.org/3.11/search.html?q=xml+rpc

P.S.: No 404 for the docs on 3.10

![screen](https://user-images.githubusercontent.com/9895620/118464091-c2bd4900-b700-11eb-9bdc-8b9212e16b2f.png)

P.S.: I initially created an issue on bpo, as I was not aware there is a dedicated project for the theme. I'll close the issue at https://bugs.python.org/issue44086

**Comment by philg314** [comment]
The broken URL was https://docs.python.org/3/_static/py.svg. I believe it was broken because the /3/ symlink was outdated, but this is now automated (see https://github.com/python/docsbuild-scripts/issues/97) so this won't happen again and this issue can be closed.

**Comment by hugovk** [comment]
Thanks for checking!
