### ISSUE TITLE
Weird monospace bug

### ISSUE THREAD

**Issue by ZedThree** [python/python-docs-theme#98]
I have some strange issues with the monospace fonts in Vivaldi (Chrome):

![image](https://user-images.githubusercontent.com/1486942/199270913-47971303-9e00-491f-ad95-af4b027ea8b5.png)

(https://docs.python.org/3/library/logging.html)

Notice how the spacing is too large and numbers seem to be unicode symbols(?)

It looks fine in Firefox:
![image](https://user-images.githubusercontent.com/1486942/199271027-ec4d277a-71bc-4bff-aa10-fcd4ed865a76.png)

I can see there were some changes last year (#85, #87). If I change the CSS to:

```css
tt, code, pre {
    font-family: monospace, monospace;
    font-size: 96.5%;
}
```

this seems to fix my issue. Having just a single `monospace` causes the text size to be a bit strange.

**Comment by ZedThree** [comment]
Vivaldi | 5.4.2753.51 (Stable channel) stable (64-bit)
-- | --
Revision | 6a886b3dacf7a1a5a6d68e6e55f92bc0abaf2aa3
OS | Linux
JavaScript | V8 10.4.132.24
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.126 Safari/537.36

**Comment by ezio-melotti** [comment]
Can you try to inspect the element and check the CSS rules that apply to that text?
It almost looks like the numbers are using Unicode fullwidth text (i.e. `２００６-０２-０８` instead of `2006-02-08`) but on that page they are ASCII.  There might be something weird going on with the monospace font used for the code blocks though -- you should be able to see that from the inspector too.

**Comment by ZedThree** [comment]
Here's the text section from the "computed styles":

![image](https://user-images.githubusercontent.com/1486942/200527885-e2d885b4-d437-49eb-886e-212675b19969.png)

There's also a bit that says "Rendered Fonts" that lists:
- DejaVu Sans Mono
- Noto Color Emoji

If I remove the quotes from `"monospace"`, or reorder them to `monospace, "monospace"` then Noto Color Emoji is removed from the list, and the text renders fine.

It's also affects function signatures:

```css
dl > dt span ~ em {
    font-family: "monospace", monospace;
}
```
![image](https://user-images.githubusercontent.com/1486942/200531173-ee97d938-ebc2-4fdc-9361-776c0b9632a3.png)

**Comment by ZedThree** [comment]
That ends up looking like this for me:

![image](https://user-images.githubusercontent.com/1486942/215540335-0b5956e3-9336-454f-8aba-59c37970cbfa.png)

which is maybe not quite nice as how Firefox renders it, but it is at least monospace. I'll make a PR for that
